[tool.poetry]
name = "mlserver_examples"
version = "0.1.0"
description = ""
authors = ["wmaucla <zhengweima@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
mlserver = "^1.3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
